---
title: "Questions and Comments"
author: "Jeff"
date: "June 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reshaping Data

I was not able to subset a column from at data frame.
```{r}
library("reshape2")
mtcars$carname<-rownames(mtcars)
head(mtcars)
```
```{r}
str(mtcars)
```

```{r}
## reshape data  
carmelt<-melt(mtcars, id=c("carname","gear","cyl"), measure.vars = c("mpg","hp"))
carmelt[c(1:3,31:34,62:64),]
```
```{r}
cylData<- dcast(carmelt, cyl ~variable)
cylData
```

```{r}
gearData<- dcast(carmelt, gear ~variable)
gearData
```
```{r}
variableData<- dcast(carmelt, variable ~gear)
variableData
```

```{r}
carmelt[carmelt$variable=="mpg"&carmelt$cyl==4,carmelt$value]
```

```{r}
a<-carmelt[carmelt$variable=="mpg"&carmelt$cyl==4,5]
a
```
```{r}
length(unique(a))
```
```{r}
length(a)
```

```{r}
cylData<-dcast(carmelt,cyl~variable, mean)
cylData
```

```{r}
cylData[2,3]
```

```{r}
head(InsectSprays)
```

```{r}
table(InsectSprays$spray)
```
```{r}
library(plyr)
ddply(InsectSprays,.(spray),summarize,sum=sum(count))
```

tapply requires same number of observations for each variable, but ddply does not.
```{r}
InsectSprays2<-InsectSprays[sample(1:72,50),]
table(InsectSprays2$spray)
```
```{r}
ddply(InsectSprays2,.(spray),summarize,sum=sum(count))
```
```{r}
ddply(InsectSprays, .(spray), summarize, sum=ave(count,FUN = sum))
```
```{r}
ddply(InsectSprays2, .(spray), summarize, sum=ave(count,FUN = sum))
```
## Managing Data Frames with dplyr - Basic Tools

```{r}
chicago <- readRDS("~/R Works/Coursera/Course 3 - Getting and Cleaning Data/Week 3/chicago.rds")
str(chicago)
```
```{r}
names(chicago)
```
```{r}
library(dplyr)
head(select(chicago,city:dptp))
```
```{r}
head(select(chicago,-(city:dptp)))
```

```{r}
head(filter(chicago,pm25tmean2>30))
```


```{r}
head(filter(chicago,pm25tmean2>30&tmpd>80))
```
```{r}
head(arrange(chicago, date))
```
```{r}
head(arrange(chicago, desc(date)))
```
```{r}
chicago1<-rename(chicago, pm25=pm25tmean2, dewpoint=dptp)
tail(chicago1)
```
```{r}
chicago2<-mutate(chicago1,pm25detrend=pm25-mean(pm25,na.rm = TRUE))
tail(select(chicago2,pm25,pm25detrend))
```
```{r}
chicago3<-mutate(chicago2,tempcat=factor(1*(tmpd>80),labels = c("cold","hot")))
hotcold<-group_by(chicago3,tempcat)
tail(hotcold)
```
```{r}
summarize(hotcold, pm25=mean(pm25, na.rm = TRUE),o3=max(o3tmean2), no2=median(no2tmean2))
```
```{r}
chicago3 %>%mutate(month=as.POSIXlt(date)$mon +1) %>% group_by(month) %>% summarize(pm25 = mean(pm25, na.rm = TRUE),o3=max(o3tmean2), no2=median(no2tmean2))
```

## Merging Data
```{r}

```
```{r}

```
```{r}

```
```{r}

```